### ISSUE TITLE
New table: actors

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#18]
### actors

- table for all subjects related to activities (table: measures) 
- can either be active "doers" or passive "targets" of an activity 

##### Permissions by role

- public: none
- registered, no role: none
- analyst: R (where draft = false, ADDED 19/10/)
- manager: CRUD
- admin: CRUD

**Comment by tmfrnz** [comment]
#### Fields

* type_id: FK > actortypes.id
* code: string
* title: text
* description: text
* url: string
* population: decimal
* gdp: decimal
* private: binary
* draft: binary

**Comment by tmfrnz** [comment]
Hi @parndt, please note that I have added one more text field "activity_summary" to this table. Cheers!

**Comment by parndt** [comment]
Thanks @tmfrnz !

**Comment by tmfrnz** [comment]
@parndt actor_type_id should have been called actortype_id as per specification (please action if easy to change)

**Comment by tmfrnz** [comment]
see #57

**Comment by parndt** [comment]
Fixed by #61

**Comment by tmfrnz** [comment]
attribute `code` should not be required and allowed to be `null` or empty, eg
- https://github.com/dumparkltd/marine-defrag-server/blob/master/db/schema.rb#L47
- https://github.com/dumparkltd/marine-defrag-server/blob/master/app/models/actor.rb#L4
