### ISSUE TITLE
New table: actor_measures

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#20]
- many-to-many join table describing an "active" link between an actor and an activity/measure (actors are understood as being responsible for executing an activity)
- has additional attributes describing the relationship
- happy to consider alternative table name

##### Permissions by role

- public: none
- registered, no role: none
- analyst: R
- manager: CRUD
- admin: CRUD

##### Rules

- only active actors where allowed for its type (`actor.actortype.is_active = true`)

**Comment by tmfrnz** [comment]
also:
- similar to the previous `last_modified_user_id` add field `updated_by` (also see https://github.com/dumparkltd/marine-defrag-server/blob/master/app/models/versioned_record.rb)
- add field `created_by` that should automatically capture the user id on creation (maybe in https://github.com/dumparkltd/marine-defrag-server/blob/master/app/models/application_record.rb?)

**Comment by tmfrnz** [comment]
please feel free to skip the field "source_id: FK >resources.id" for now and add it once the resources table will have been created (#28)

**Comment by tmfrnz** [comment]
rename table to actor_measures as specified and consistent with previous join tables

**Comment by tmfrnz** [comment]
@parndt: maybe I am missing something but is it possible that the `create` and `delete` functions/endpoints have not yet been specified?

**Comment by tmfrnz** [comment]
in fact, given that this table also includes info on the relationship, we will also need the `update` function/endpoint

**Comment by tmfrnz** [comment]
getting error when creating entity:
`ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "created_by_id" of relation "actor_measures" violates not-null constraint`

likely also affects #21

**Comment by tmfrnz** [comment]
likely this is caused by the `not null` constraint defined that is not present for other tables:

https://github.com/dumparkltd/marine-defrag-server/blob/master/db/schema.rb#L37
```
  create_table "actor_measures", force: :cascade do |t|
    t.bigint "actor_id", null: false
    t.bigint "measure_id", null: false
    t.date "date_start"
    t.date "date_end"
    t.decimal "value"
    t.bigint "created_by_id", null: false <<<<<<<<<<<<<<<<<<<<<<<<
    t.bigint "updated_by_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
```

eg compare to 
https://github.com/dumparkltd/marine-defrag-server/blob/master/db/schema.rb#L219
```
  create_table "measures", id: :serial, force: :cascade do |t|
    t.text "title", null: false
    t.text "description"
    t.text "target_date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "draft", default: false
    t.text "outcome"
    t.text "indicator_summary"
    t.text "target_date_comment"
    t.integer "updated_by_id"
    t.integer "created_by_id" <<<<<<<<<<<<<<<<<<<<<<<<
```
```

**Comment by tmfrnz** [comment]
so while I suspect this could be fixed by simply dropping the constraint here, it might also be possible to fix this by making sure the user is available before validating these constraints

**Comment by parndt** [comment]
@tmfrnz how do you want to handle the seeds file? Which user will all these records be created by?

**Comment by tmfrnz** [comment]
`actor_measures` records will not be created by a seeds file but only through the client 

the seeds file will pretty much only contain non-editable records (`roles`, `*types`, `taxonomies`, `*type_taxonomies`. the only editable records will be `categories` that will only be linked to their `taxonomy` but not to any (non-existing `actors`, or `measures`

**Comment by tmfrnz** [comment]
also see https://github.com/dumparkltd/marine-defrag-server/pull/79#issuecomment-968709378
