### ISSUE TITLE
New table: actortypes

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#22]
- configuration table for the different types of actors
- i.e. country (active/passive), organisation (active), group (of countries and actors, active), region (of countries, passive), class (of countries, passive) (corresponds to existing table "frameworks")
- defines if actors can be "active" or "passive" with regards to an activity
- defines if actors can have members (`has_members`)

##### Permissions by role

- public: none
- registered, no role: none
- analyst: R
- manager: R
- admin: R

**Comment by tmfrnz** [comment]
@parndt if easy to change please change name from actor_types to actortypes as per specification

**Comment by tmfrnz** [comment]
see #57

**Comment by parndt** [comment]
Fixed by #61
