### ISSUE TITLE
New table: actortype_taxonomies

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#23]
- simple many-to-many "join" table linking actortypes with taxonomies 
- determines which taxonomy categories may be applied to an actor by type
- corresponds to existing table "framework_taxonomies"
- configuration table

##### Permissions by role

- public: none
- registered, no role: none
- analyst: R
- manager: R
- admin: R

**Comment by tmfrnz** [comment]
@parndt if easy to change please change name from actor_type_taxonomies to actortype_taxonomies as per specification

**Comment by tmfrnz** [comment]
see #57

**Comment by parndt** [comment]
Fixed by #61

**Comment by tmfrnz** [comment]
rename table to actortype_taxonomies as specified and consistent with previous join tables
