### ISSUE TITLE
New table: measuretypes

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#25]
- table for the different types of activities/measures
- different knowledge categories, e.g. conventions, strategies, initiatives, donor activities
- defines if activities can have target/passive actors and parents

##### Permissions by role

- public: none
- registered, no role: none
- analyst: R
- manager: R
- admin: R

**Comment by tmfrnz** [comment]
@parndt if easy to change please change name from measure_types to measuretypes as per specification

**Comment by tmfrnz** [comment]
see #57

**Comment by parndt** [comment]
Fixed by #61
