### ISSUE TITLE
Update table: measures

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#31]
- several new fields (see below)
- introducing parent relationship where a measure can belong to another one (eg predecessor)

##### Permissions by role

- public: none
- registered, no role: none
- analyst: R  (where draft = false, ADDED 19/10/)
- manager: CRUD
- admin: CRUD

##### Rules 

- a measure can't be its own parent (`parent_id != id`)
- a measure can only be a parent when allowed for its type (`measure.measuretype.has_parent = true`)
- NEW (7/10/): a measure's ancestor can't also be its descendant (we can have A < B < C but not A < B < A or A < B < C < A)

**Comment by tmfrnz** [comment]
#### new fields

- type_id: FK > measuretypes.id
- parent_id: FK > measure.id
- code: text
- comment: text
- url: string/text
- date_start: datetime
- date_end: datetime
- date_comment: text
- target_comment: text
- status_comment: text
- reference_ml: text
- reference_landbased_ml: text
- has_reference_landbased_ml: boolean
- status_lbs_protocol: text
- amount: decimal
- amount_comment: text
- private: boolean

**Comment by tmfrnz** [comment]
also:
- rename `last_modified_user_id` to `updated_by` (also see https://github.com/dumparkltd/marine-defrag-server/blob/master/app/models/versioned_record.rb)
- add field `created_by` that should automatically capture the user id on creation (maybe in https://github.com/dumparkltd/marine-defrag-server/blob/master/app/models/application_record.rb?)

**Comment by parndt** [comment]
> rename `last_modified_user_id` to `updated_by` (also see [`master`/app/models/versioned_record.rb](https://github.com/dumparkltd/marine-defrag-server/blob/master/app/models/versioned_record.rb))

@tmfrnz `updated_by` or `updated_by_id`?

**Comment by parndt** [comment]
> add field `created_by` that should automatically capture the user id on creation (maybe in [`master`/app/models/application_record.rb](https://github.com/dumparkltd/marine-defrag-server/blob/master/app/models/application_record.rb)?)

`created_by` or `created_by_id`?

**Comment by parndt** [comment]
The reason I ask is because of how Rails works the column should be named `created_by_id` and `updated_by_id` but the API can return them without the `_id` if you want?

**Comment by tmfrnz** [comment]
@parndt accordingly measure_type_id should be measuretype_id as per specification

**Comment by tmfrnz** [comment]
see #57

**Comment by parndt** [comment]
Fixed by #61
