### ISSUE TITLE
Update table: users

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#34]
- no changes to schema

##### Permissions by role

- public: C (register)
- registered, no role: RU (own record only)
- analyst: RU (own record only)
- manager: R (all user records), U (own record only)
- admin: RU ~D~ (all user records)

**Comment by tmfrnz** [comment]
quick note that I believe the main thing missing here is that registered users without role (aka "guest" users) should be able to Read and Update their own record

**Comment by parndt** [comment]
> quick note that I believe the main thing missing here is that registered users without role (aka "guest" users) should be able to Read and Update their own record

and, I think, restrictions on destroy + ability to register a new user

**Comment by parndt** [comment]
> destroy on all other records should only be possible for manager and admin users

do you mean that just admin users can destroy other user records?

**Comment by tmfrnz** [comment]
No, no one should be able to destroy "user records" via the API. Which is different from how we handle all other tables, where users with admin and manager roles can destroy records via the API
