### ISSUE TITLE
db:migrate failing on Heroku: create_table called with wrong number of arguments (2 instead of 1)

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#51]
while trying to set up the app on Heroku, I encountered the following error when running db:migrate, specifically https://github.com/dumparkltd/marine-defrag-server/blob/master/db/migrate/20170107173635_create_versions.rb#L19:

```
[...]
== 20170107173635 CreateVersions: migrating ===================================
D, [2021-10-29T11:37:13.319120 #4] DEBUG -- :    (0.6ms)  SELECT pg_advisory_unlock(2946749598466660140)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 2, expected 1)
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/migration/compatibility.rb:175:in `create_table'
[...]
```

**Comment by parndt** [comment]
Yes there probably is!  In the meantime I've worked around it by running db:schema:load and then migrate 

I'll take a look at this error as probably there's just a new way to do it
