### ISSUE TITLE
Naming of *type tables

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#57]
Hi @parndt, sorry to raise this so late but the *types table names should ideally not include the `_` as I prefer it to indicate the existence of a many-many join table (joining the left with the right part). 

Eg calling it `actortypes` it is clear that it does not join `actors` with `types` but instead is a concept in its own right. Likewise `actortype_taxonomies` clearly joins actortypes with taxonomies (whereas `actor_type_taxonomies` does not allow to infer this).

I realise that we have other tables inconsistent with this convention (eg `due_dates` and `progress_reports` that should have been called `duedates` and `progressreports`) but please leave them for now (they have never been used in m:n join tables so we never ended up with a confusing double `_`)

**Comment by tmfrnz** [comment]
so yeah if its not too much work (or if there are other reasons against doing so), it would be great if you could change 

- the table names (eg actor_type > actortype, actor_type_taxonomies > actortype_taxonomies)
- all foreign key references (eg actor_type_id > actortypeid)
- maybe even the model names (ActorType > Actortype) for consistency

**Comment by tmfrnz** [comment]
if its a hassle maybe for now at least renaming the endpoints would be awesome so we won't have to change the client code

**Comment by tmfrnz** [comment]
re-opening those tables as I think this should be addressed eventually fully addressed

**Comment by parndt** [comment]
@tmfrnz all good, this isn't too bad to fix 😄
