### ISSUE TITLE
app server crashes 

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#58]
error when running procfile  `Could not find server "".` 

likely due to missing -u option `-u, [--using=name]  # Specifies the Rack server used to run the application (thin/puma/webrick)`

**Comment by tmfrnz** [comment]
@parndt I added the option here (https://github.com/dumparkltd/marine-defrag-server/commit/956b5238f007cba4dcf615083b362ce16ad2b0f7) but I failed to add webrick to the gemfile that is no longer part of ruby 3 [see here](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/)
(bundle install crashing on my win machine)

could you please add webrick to the gemfile or otherwise make sure the server command runs? thanks

**Comment by tmfrnz** [comment]
> @parndt I added the option here ([956b523](https://github.com/dumparkltd/marine-defrag-server/commit/956b5238f007cba4dcf615083b362ce16ad2b0f7)) but I failed to add webrick to the gemfile that is no longer part of ruby 3 ([see here](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/))
> 
> could you please add webrick to the gemfile or otherwise make sure the server command runs? thanks

branch is fix-server btw: https://github.com/dumparkltd/marine-defrag-server/compare/fix-server

**Comment by tmfrnz** [comment]
related ruby update https://github.com/dumparkltd/marine-defrag-server/commit/9196e8db6fab8d11492bb1be132e04326944039c

**Comment by tmfrnz** [comment]
in addition to adding and using puma gem, I also had to setup a config file for active storage

**Comment by tmfrnz** [comment]
> in the meantime I will try to fix my bundle/installation issues, currently failing on
> 
> ```
> An error occurred while installing kgio (2.11.4), and Bundler cannot continue.
> Make sure that `gem install kgio -v '2.11.4' --source 'https://rubygems.org/'`
> succeeds before bundling.
> 
> In Gemfile:
>   unicorn-worker-killer was resolved to 0.4.5, which depends on
>     unicorn was resolved to 6.0.0, which depends on
>       kgio
> ```

while failing on my windows machine, I was able to run it on our macbook

**Comment by parndt** [comment]
@tmfrnz good work! I think we should remove `unicorn` & `unicorn-worker-killer` too

**Comment by tmfrnz** [comment]
Yes definitely some weeding out to be done
