### ISSUE TITLE
Naming of join tables

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#63]
For consistency with existing tables (and with the endpoints also), all join tables should be named by combining names of related tables where the first name is singular and the second name plural, 

Original examples include

- user_roles, joining users and roles
- measure_categories, joining measures and categories

New examples that need fixing are

- [x] actor_measures #20
- [x] measure_actors #21
- [x] actortype_taxonomies #23 
- [x] measuretype_taxonomies #26

**Comment by parndt** [comment]
@tmfrnz all good - easy change! Sorry about that, I autopiloted the Rails conventions instead of naming based on the diagram. 👍

**Comment by tmfrnz** [comment]
thanks so much and apologies for being so pedantic here!

**Comment by parndt** [comment]
No worries 😄
