### ISSUE TITLE
Review and test docker setup

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#83]
@parndt when you have time it would be great if you could quickly review the docker setup (I think this would be the best way to install it on the target server but please let me know if you think otherwise)

* have created a new branch to try things out [docker-config](https://github.com/dumparkltd/marine-defrag-server/tree/docker-config)
* was able to run `docker-compose up` locally 
* running `docker-compose run app rake db:setup` is giving me errors though, likely related to my configuration

```
could not translate host name "db" to address: Temporary failure in name resolion
Couldn't create 'marine_defrag_development' database. Please check your configuration.
rake aborted!
ActiveRecord::ConnectionNotEstablished: could not translate host name "db" to dress: Temporary failure in name resolution
```

**Comment by parndt** [comment]
@tmfrnz got it working

<img width="488" alt="image" src="https://user-images.githubusercontent.com/10128/141949847-993e83b4-3174-4113-9834-272e6c54d90d.png">

I pushed to the branch 😄 you may have to run `docker-compose build` then run `docker-compose up` and then `docker-compose run app rake db:setup`

**Comment by tmfrnz** [comment]
awesome, thanks so much for looking into it right away! I will try to get this going on the target system today and let you know (if I fail would you be able to have a look if I provide you with the gridscale login and ssh details?
